"""
Clean up auto-generated notifications from camera modules.
These notifications should not exist - alerts are already in dedicated alert models.
"""
import os
import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'flame_guard_project.settings')
django.setup()

from admin_module.models import Notification

# Delete notifications that were auto-generated by camera modules
# These have titles like "🔥 Fire at...", "🐅 Wildlife:...", "🚶 Intrusion at..."
auto_generated_patterns = [
    '🔥 Fire at',
    '🐅 Wildlife:',
    '🚶 Intrusion at',
    'Intrusion at',
    'Wildlife:',
    'Fire at'
]

deleted_count = 0
for pattern in auto_generated_patterns:
    count = Notification.objects.filter(title__contains=pattern).delete()[0]
    deleted_count += count
    if count > 0:
        print(f"✓ Deleted {count} notifications matching '{pattern}'")

print(f"\n✅ Total deleted: {deleted_count} auto-generated notifications")
print("ℹ️  Officers can still see all alerts in their dedicated alert pages:")
print("   - Fire Alerts page")
print("   - Animal Detection page")
print("   - Human Intrusions page")
