from django.db import models

class ForestOfficer(models.Model):
    """
    Stores extra details for Forest Officers.
    Linked to the main CustomUser (login info) and their workspace (ForestStation).
    """
    user = models.OneToOneField('admin_module.CustomUser', on_delete=models.CASCADE, related_name='officer_profile')
    station = models.ForeignKey('admin_module.ForestStation', on_delete=models.SET_NULL, null=True, blank=True)
    designation = models.CharField(max_length=100) # e.g. "Range Officer"
    badge_number = models.CharField(max_length=50, blank=True)

    def __str__(self):
        return f"{self.user.username} - {self.designation}"


# ================================
# USER ALERT SYSTEM
# ================================
class UserAlert(models.Model):
    """
    Alerts sent by Forest Officers to public users.
    E.g., "Tiger spotted in Area X", "Forest closed for maintenance"
    """
    ALERT_TYPE_CHOICES = (
        ('WARNING', 'Warning'),
        ('INFO', 'Information'),
        ('DANGER', 'Danger'),
        ('CLOSURE', 'Area Closure'),
    )
    
    officer = models.ForeignKey('admin_module.CustomUser', on_delete=models.CASCADE, related_name='sent_user_alerts', limit_choices_to={'user_type': 'OFFICER'})
    title = models.CharField(max_length=200)
    message = models.TextField()
    alert_type = models.CharField(max_length=10, choices=ALERT_TYPE_CHOICES, default='INFO')
    location = models.CharField(max_length=200, blank=True)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    expires_at = models.DateTimeField(null=True, blank=True)
    
    def __str__(self):
        return f"{self.title} - {self.officer.username}"
    
    class Meta:
        ordering = ['-created_at']


# ================================
# HUMAN INTRUSION DETECTION
# ================================
class HumanIntrusionAlert(models.Model):
    """
    Alerts when humans are detected in restricted forest areas.
    Generated by camera module AI.
    """
    STATUS_CHOICES = (
        ('NEW', 'New'),
        ('INVESTIGATING', 'Investigating'),
        ('RESOLVED', 'Resolved'),
        ('FALSE_ALARM', 'False Alarm'),
    )
    
    station = models.ForeignKey('admin_module.ForestStation', on_delete=models.CASCADE, related_name='intrusion_alerts')
    detected_at = models.DateTimeField(auto_now_add=True)
    location_details = models.TextField(blank=True)
    image = models.ImageField(upload_to='intrusions/', blank=True, null=True)
    status = models.CharField(max_length=15, choices=STATUS_CHOICES, default='NEW')
    officer_notified = models.BooleanField(default=False)
    notes = models.TextField(blank=True)
    resolved_at = models.DateTimeField(null=True, blank=True)
    
    def __str__(self):
        return f"Intrusion at {self.station.name} - {self.detected_at.strftime('%Y-%m-%d %H:%M')}"
    
    class Meta:
        ordering = ['-detected_at']


# ================================
# USER NOTIFICATION SYSTEM
# ================================
class UserNotification(models.Model):
    """
    Notifications sent to public users when a fire alert occurs.
    Scoped to a specific division — only users in that division receive them.
    """
    NOTIF_TYPE_CHOICES = (
        ('FIRE_ALERT', 'Fire Alert'),
        ('STATUS_UPDATE', 'Status Update'),
    )

    fire_alert = models.ForeignKey(
        'admin_module.FireAlert',
        on_delete=models.CASCADE,
        related_name='user_notifications'
    )
    recipient = models.ForeignKey(
        'admin_module.CustomUser',
        on_delete=models.CASCADE,
        related_name='user_notifications'
    )
    title = models.CharField(max_length=255)
    body = models.TextField()
    notif_type = models.CharField(max_length=15, choices=NOTIF_TYPE_CHOICES, default='FIRE_ALERT')
    is_read = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.title} → {self.recipient.username}"

    class Meta:
        ordering = ['-created_at']


# ================================
# ANIMAL DETECTION ALERTS
# ================================
class AnimalAlert(models.Model):
    """
    Alerts when animals are detected in forest areas.
    Generated by camera module AI.
    """
    STATUS_CHOICES = (
        ('NEW', 'New'),
        ('ACKNOWLEDGED', 'Acknowledged'),
        ('INVESTIGATING', 'Investigating'),
        ('RESOLVED', 'Resolved'),
    )
    
    SEVERITY_CHOICES = (
        ('LOW', 'Low'),
        ('MEDIUM', 'Medium'),
        ('HIGH', 'High'),
        ('CRITICAL', 'Critical'),
    )
    
    station = models.ForeignKey('admin_module.ForestStation', on_delete=models.CASCADE, related_name='animal_alerts')
    animal_type = models.CharField(max_length=100)  # e.g., "Tiger", "Elephant"
    detected_at = models.DateTimeField(auto_now_add=True)
    location_details = models.TextField(blank=True)
    confidence_score = models.FloatField(default=0.0)  # AI confidence (0.0 to 1.0)
    severity = models.CharField(max_length=10, choices=SEVERITY_CHOICES, default='MEDIUM')
    status = models.CharField(max_length=15, choices=STATUS_CHOICES, default='NEW')
    image = models.ImageField(upload_to='animals/', blank=True, null=True)
    officer_notified = models.BooleanField(default=False)
    notes = models.TextField(blank=True)
    resolved_at = models.DateTimeField(null=True, blank=True)
    
    def __str__(self):
        return f"{self.animal_type} at {self.station.name} - {self.detected_at.strftime('%Y-%m-%d %H:%M')}"
    
    class Meta:
        ordering = ['-detected_at']
