# Generated by Django 6.0 on 2026-01-07 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0002_complaint_firealert_notification_preservedanimal_and_more'),
        ('officer_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HumanIntrusionAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('location_details', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='intrusions/')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('INVESTIGATING', 'Investigating'), ('RESOLVED', 'Resolved'), ('FALSE_ALARM', 'False Alarm')], default='NEW', max_length=15)),
                ('officer_notified', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intrusion_alerts', to='admin_module.foreststation')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('alert_type', models.CharField(choices=[('WARNING', 'Warning'), ('INFO', 'Information'), ('DANGER', 'Danger'), ('CLOSURE', 'Area Closure')], default='INFO', max_length=10)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('officer', models.ForeignKey(limit_choices_to={'user_type': 'OFFICER'}, on_delete=django.db.models.deletion.CASCADE, related_name='sent_user_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
