# Generated by Django 4.2.11 on 2026-01-13 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0003_alter_animal_id_alter_complaint_id_and_more'),
        ('officer_module', '0002_humanintrusionalert_useralert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forestofficer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='humanintrusionalert',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='useralert',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='AnimalAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_type', models.CharField(max_length=100)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('location_details', models.TextField(blank=True)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ACKNOWLEDGED', 'Acknowledged'), ('INVESTIGATING', 'Investigating'), ('RESOLVED', 'Resolved')], default='NEW', max_length=15)),
                ('image', models.ImageField(blank=True, null=True, upload_to='animals/')),
                ('officer_notified', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_alerts', to='admin_module.foreststation')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
    ]
