# Generated by Django 4.2.11 on 2026-02-24 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0005_customuser_division_alter_animal_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('officer_module', '0003_alter_forestofficer_id_alter_humanintrusionalert_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('notif_type', models.CharField(choices=[('FIRE_ALERT', 'Fire Alert'), ('STATUS_UPDATE', 'Status Update')], default='FIRE_ALERT', max_length=15)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fire_alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to='admin_module.firealert')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
