# Generated by Django 4.2.11 on 2026-01-13 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('officer_module', '0003_alter_forestofficer_id_alter_humanintrusionalert_id_and_more'),
        ('admin_module', '0003_alter_animal_id_alter_complaint_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firealert',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_fire_alerts', to='officer_module.forestofficer'),
        ),
    ]
