# Generated by Django 4.2.11 on 2026-02-24 05:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0004_firealert_resolved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='admin_module.forestdivision'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='description',
            field=models.TextField(validators=[django.core.validators.RegexValidator(code='invalid_description', message='Description must contain alphabetic characters. Numbers alone are not allowed.', regex='[a-zA-Z]')]),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='subject',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(code='invalid_subject', message='Subject must contain only letters and spaces.', regex='^[A-Za-z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='forestdivision',
            name='location',
            field=models.CharField(blank=True, max_length=200, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Only alphabets and spaces are allowed', regex='^[A-Za-z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='forestdivision',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Only alphabets and spaces are allowed', regex='^[A-Za-z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='foreststation',
            name='contact_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(code='invalid_contact_number', message='Contact number must be exactly 10 digits', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='foreststation',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Only alphabets and spaces are allowed', regex='^[A-Za-z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='preservedanimal',
            name='population_estimate',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999, message='Population estimate must be a numeric value with a maximum of 6 digits.')]),
        ),
    ]
