# Generated by Django 4.2.11 on 2026-03-10 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0005_customuser_division_alter_animal_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
