# Generated by Django 4.2.11 on 2026-05-04 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0006_customuser_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficerComplaint',
            fields=[
            ],
            options={
                'verbose_name': 'Officer Complaint',
                'verbose_name_plural': 'Officer Complaints',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('admin_module.complaint',),
        ),
        migrations.CreateModel(
            name='UserComplaint',
            fields=[
            ],
            options={
                'verbose_name': 'User Complaint',
                'verbose_name_plural': 'User Complaints',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('admin_module.complaint',),
        ),
    ]
